-- SELECT *, (SELECT id FROM wishlist WHERE wishlist.product_id = products_view.id AND user_id = "61") as wishlist FROM products_view WHERE is_delete = "1" AND (`product_title_name` LIKE "%%" OR `product_description` LIKE "%%" OR `product_type` LIKE "%%" OR `colors` LIKE "%%" ) LIMIT 0,500"
-- "SELECT *, (SELECT id FROM wishlist WHERE wishlist.product_id = products_view.id AND user_id = "62") as wishlist FROM products_view WHERE is_delete = "1" AND (`product_price` BETWEEN "20" AND "500000")  AND is_delete = "1"  LIMIT 0,10"
-- SELECT * FROM `products` WHERE FIND_IN_SET('18',parent_category)
-- SELECT`id`, `user_id`, `status`, `created_on`, `order_id`, `product_id`, `sale_price`, `shipping_charges`, `gst`, `parent_category`, `vendor_id`, `is_delete` FROM `orders_view` WHERE created_on BETWEEN '2022-11-28 00:00:00' AND '2022-11-29 23:59:59

-- CREATE VIEW products_view4 AS SELECT products_pricing.id,products_pricing.product_id,products.product_title_name,products.product_slug,products.store_name,products.product_description,products.product_type,products.brand,products.category,products.parent_category,products.seo_tag,products.other_introduction,products.add_custom_input,products.wholesale_sales_tax,products.manufacturers_sales_tax,products.retails_sales_tax,products.gst,products.value_added_tax,products.variety,products.vendor_id,products.shop,products.rating,products_pricing.colors,products_pricing.size,products_pricing.mrp,products_pricing.product_price,products_pricing.sale_price,products_pricing.discount,products_pricing.manufacturing_date,products_pricing.expire_date,products_pricing.special_offer,products_pricing.featured_product,products_pricing.unit,products_pricing.unit_quantity,products_pricing.quantity,products_pricing.is_delete,products_pricing.product_status,products.cgst,products.sgst,(SELECT GROUP_CONCAT(product_image_path) FROM product_images WHERE product_images.product_verient_id = products_pricing.id group by product_verient_id) as all_images FROM products_pricing,products WHERE products_pricing.product_id = products.id



SELECT *, (SELECT id FROM wishlist WHERE wishlist.product_id = products_view.id AND user_id = "61") as wishlist, (SELECT is_deleted FROM fetured_product_table WHERE fetured_product_table.product_id = products_view.product_id AND fetured_product_table.start_date < NOW() AND fetured_product_table.end_date > NOW() ) as is_fetured_product FROM products_view WHERE is_delete = "1" AND  is_fetured_product IN ("1") AND is_delete = "1"  LIMIT 0,10


CREATE VIEW products_view AS SELECT products_pricing.id,products_pricing.product_id,products.product_title_name,products.product_slug,products.store_name,products.product_description,products.product_type,products.brand,products.category,products.parent_category,products.seo_tag,products.other_introduction,products.add_custom_input,products.wholesale_sales_tax,products.manufacturers_sales_tax,products.retails_sales_tax,products.gst,products.value_added_tax,products.variety,products.vendor_id,products.shop,products.rating,products_pricing.colors,products_pricing.size,products_pricing.mrp,products_pricing.product_price,products_pricing.sale_price,products_pricing.discount,products_pricing.manufacturing_date,products_pricing.expire_date,products_pricing.special_offer,products_pricing.featured_product,products_pricing.unit,products_pricing.unit_quantity,products_pricing.quantity,products_pricing.is_delete,products_pricing.product_status,products.cgst,products.sgst,(SELECT GROUP_CONCAT(product_image_path) FROM product_images WHERE product_images.product_verient_id = products_pricing.id AND image_position = 'cover' group by product_verient_id) as all_images,(SELECT id FROM fetured_product_table WHERE fetured_product_table.product_id = products_pricing.product_id AND fetured_product_table.start_date < NOW() AND fetured_product_table.end_date > NOW() ) as fetured_product_id ,(SELECT is_deleted FROM fetured_product_table WHERE fetured_product_table.product_id = products_pricing.product_id AND fetured_product_table.start_date < NOW() AND fetured_product_table.end_date > NOW() ) as is_fetured_product, (SELECT fetured_type FROM fetured_product_table WHERE fetured_product_table.product_id = products_pricing.product_id AND fetured_product_table.start_date < NOW() AND fetured_product_table.end_date > NOW() ) as fetured_type FROM products_pricing,products WHERE products_pricing.product_id = products.id